---
- key: application_id
  value: '0'
- key: me
  value: '1'
- key: default_locale
  value: 'en'
- key: mailchimp_list_name
  value: 'name'
- key: mailchimp_api_key
  value: '00000000000000000000000000000000-us0'
- key: mailchimp_connection_secure
  value: 'true'
- key: mailchimp_connection_timeout
  value: '120'
- key: invoices_prefix
  value: invoices
- key: invoices_debit_account
  value: 'changeme'
- key: invoices_credit_account
  value: 'changeme'
- key: invoices_vat_code
  value: 'changeme'
- key: receipts_prefix
  value: receipts
- key: receipts_debit_account
  value: 'changeme'
- key: receipts_credit_account
  value: 'changeme'
- key: receipts_vat_code
  value: '1300'
- key: salaries_prefix
  value: salary
- key: salaries_employee_deductions_prefix
  value: employee deductions
- key: salaries_employer_deductions_prefix
  value: employer deductions
- key: banana_accounting_headers_mapping
  value: '{"Date": "date", "Description": "description", "Amount": "value", "AccountDebit": "account", "AccountCredit": "counterpart_account"}'
- key: export_invoice_description
  value: '{"attributes": ["id", "title", "owner.try(:name)", "owner.try(:id)"], "separator": "/"}'
- key: export_receipt_description
  value: '{"attributes": ["id", "invoice.title", "owner.try(:name)", "owner.try(:id)"], "separator": "/"}'
- key: export_salary_description
  value: ''
- key: export_salary_and_taxes_description
  value: '{"attributes": ["id", "title", "person.try(:name)", "person.try(:id)", "from.strftime(\"%d-%m\")", "to.strftime(\"%d-%m\")"], "separator": "/"}'
- key: service_vat_rate
  value: '8.0'
- key: service_vat_number
  value: 'CHE-123.456.789 TVA'
- key: use_vat
  value: 'true'
- key: default_currency
  value: 'CHF'
- key: default_affair_conditions
  value: 'pay to confirm order'
- key: default_invoice_conditions
  value: '10 days'
- key: default_product_category_name
  value: 'Product'
- key: affairs_description_placeholder
  value: 'edit me in application settings: affairs_description_placeholder'
- key: affairs_notes_placeholder
  value: 'edit me in application settings: affairs_notes_placeholder'
- key: affairs_footer_placeholder
  value: 'edit me in application settings: affairs_footer_placeholder'
- key: affairs_execution_notes_placeholder
  value: 'edit me in application settings: affairs_execution_notes_placeholder'
- key: product_item_warning_threshold
  value: '2.month'
- key: product_item_danger_threshold
  value: '1.month'
- key: creditor_prefix
  value: creditor
- key: creditor_account
  value: 'changeme'
- key: creditor_vat_code
  value: 'changeme'
- key: export_creditor_description
  value: '{"attributes": ["id", "title", "creditor.try(:name)", "creditor.try(:id)", "affair.try(:title)"], "separator": "/"}'
