---
- subject: Person
  action: restricted_attributes
  hash_conditions: '{:id => user.id}'

- subject: Task
  action: manage
  hash_conditions: '{:person_id => user.id}'

- subject: TaskType
  action: read

- subject: TaskRate
  action: read

- subject: Product
  action: manage

- subject: ProductProgram
  action: manage

- subject: ProductVariant
  action: manage

- subject: AffairsProductsProgram
  action: manage

- subject: AffairsProductsCategory
  action: manage

- subject: Extra
  action: manage

- subject: GenericTemplate
  action: index

- subject: GenericTemplate
  action: placeholders

- subject: GenericTemplate
  action: count

- subject: Person
  action: dashboard_comments

- subject: Person
  action: dashboard_activities

- subject: Person
  action: dashboard_current_affairs